[package]
name = "diffrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.0.79"
range_minimum_query = "0.1.0"

[build-dependencies]
cc = "1.0.79"

[profile.release]
debug = 2
